# conda environment for training Pose Model

#
# To activate this environment, use
#
#     $ conda activate PoseDetectorDLCLive
#
# To deactivate an active environment, use
#
#     $ conda deactivate

# have to mix conda and pip, as the conda resolver isn't able to finish

name: PoseDetectorDLCLive_Training
channels:
   - conda-forge
   - defaults
dependencies:
   - python=3.8
   - pip
   - ipython
   - pip:
     - jupyter
     - tensorflow==2.11
     - keras==2.11
     - numpy
     - pandas
     - mlflow
     - dvc-gdrive
   - nb_conda
