# PoseDetector.yaml

### based on
#DeepLabCut2.0 Toolbox (deeplabcut.org)
#© A. & M. Mathis Labs
#https://github.com/DeepLabCut/DeepLabCut
#Please see AUTHORS for contributors.

#https://github.com/DeepLabCut/DeepLabCut/blob/master/AUTHORS
#Licensed under GNU Lesser General Public License v3.0
#
# DeepLabCut environment
# FIRST: INSTALL CORRECT DRIVER for GPU, see https://stackoverflow.com/questions/30820513/what-is-the-correct-version-of-cuda-for-my-nvidia-driver/30820690

### Additions
# MLFlow
# DVC (gdrive, change if you want to use other storage)

###
# install:    conda env create -f conda_env.yaml
# update:     conda env update -f conda_env.yaml
# activate:   conda activate PoseDetectorDLCModel
# deactivate: conda deactivate

name: PoseDetectorDLCModel
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - ipython
  - ffmpeg
  - pip:
    - PyQt6
    - jupyter
    - "deeplabcut[gui,tf]==2.3.0"
    - mlflow
    - dvc-gdrive
  - nb_conda
