# conda environment for training Pose Model

#
# To activate this environment, use
#
#     $ conda activate PoseDetectorDLCLive_Prediction
#
# To deactivate an active environment, use
#
#     $ conda deactivate

# have to mix conda and pip, as the conda resolver isn't able to finish

name: PoseDetectorDLCLive_Prediction
channels:
   - conda-forge
   - defaults
dependencies:
   - python=3.8
   - tensorflow # TODO same version as in Training, specify
   - pip
   - numpy
   - pip:
     - deeplabcut-live
     - opencv-contrib-python
     - imagezmq
     - mlflow
     - dvc-gdrive
